{
    "name": "Autoboutique Vehicle Operations",
    "version": "19.0.1.8.1",
    "summary": "Vehicle acquisition, inspection, repair, materials, and detailing",
    "author": "Prime Auto Boutique",
    "category": "Inventory",
    "license": "LGPL-3",
    "depends": ["base", "mail", "product", "purchase", "stock", "sale_management", "account"],
    "data": [
        "security/roles.xml",
        "security/ir.model.access.csv",
        "security/company_rules.xml",
        "data/ir_cron.xml",
        "data/qc_checklist_data.xml",
        "views/operations_views.xml",
        "views/extended_views.xml",
        "views/automation_views.xml",
        "views/qc_checklist_views.xml",
        "report/qc_checklist_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "autoboutique_ops/static/src/js/company_switch_reload.js",
            "autoboutique_ops/static/src/dashboard/management_dashboard.js",
            "autoboutique_ops/static/src/dashboard/management_dashboard.xml",
            "autoboutique_ops/static/src/dashboard/management_dashboard.scss",
        ],
    },
    "application": True,
    "installable": True,
}
